package com.kuviam.dopa.model;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.kuviam.dopa.model.Locus;
import com.kuviam.dopa.model.Locus_text_list;
import com.kuviam.dopa.model.Locus_image_list;
import com.kuviam.dopa.model.Locus_sound_list;
import com.kuviam.dopa.model.Locus_number_list;
import com.kuviam.dopa.model.Discipline;
import com.kuviam.dopa.model.Discipline_text_list;
import com.kuviam.dopa.model.Discipline_image_list;
import com.kuviam.dopa.model.Discipline_sound_list;
import com.kuviam.dopa.model.Discipline_number_list;
import com.kuviam.dopa.model.Run;
import com.kuviam.dopa.model.Run_discipline_item_list;
import com.kuviam.dopa.model.Dictionary;

import com.kuviam.dopa.model.LocusDao;
import com.kuviam.dopa.model.Locus_text_listDao;
import com.kuviam.dopa.model.Locus_image_listDao;
import com.kuviam.dopa.model.Locus_sound_listDao;
import com.kuviam.dopa.model.Locus_number_listDao;
import com.kuviam.dopa.model.DisciplineDao;
import com.kuviam.dopa.model.Discipline_text_listDao;
import com.kuviam.dopa.model.Discipline_image_listDao;
import com.kuviam.dopa.model.Discipline_sound_listDao;
import com.kuviam.dopa.model.Discipline_number_listDao;
import com.kuviam.dopa.model.RunDao;
import com.kuviam.dopa.model.Run_discipline_item_listDao;
import com.kuviam.dopa.model.DictionaryDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig locusDaoConfig;
    private final DaoConfig locus_text_listDaoConfig;
    private final DaoConfig locus_image_listDaoConfig;
    private final DaoConfig locus_sound_listDaoConfig;
    private final DaoConfig locus_number_listDaoConfig;
    private final DaoConfig disciplineDaoConfig;
    private final DaoConfig discipline_text_listDaoConfig;
    private final DaoConfig discipline_image_listDaoConfig;
    private final DaoConfig discipline_sound_listDaoConfig;
    private final DaoConfig discipline_number_listDaoConfig;
    private final DaoConfig runDaoConfig;
    private final DaoConfig run_discipline_item_listDaoConfig;
    private final DaoConfig dictionaryDaoConfig;

    private final LocusDao locusDao;
    private final Locus_text_listDao locus_text_listDao;
    private final Locus_image_listDao locus_image_listDao;
    private final Locus_sound_listDao locus_sound_listDao;
    private final Locus_number_listDao locus_number_listDao;
    private final DisciplineDao disciplineDao;
    private final Discipline_text_listDao discipline_text_listDao;
    private final Discipline_image_listDao discipline_image_listDao;
    private final Discipline_sound_listDao discipline_sound_listDao;
    private final Discipline_number_listDao discipline_number_listDao;
    private final RunDao runDao;
    private final Run_discipline_item_listDao run_discipline_item_listDao;
    private final DictionaryDao dictionaryDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        locusDaoConfig = daoConfigMap.get(LocusDao.class).clone();
        locusDaoConfig.initIdentityScope(type);

        locus_text_listDaoConfig = daoConfigMap.get(Locus_text_listDao.class).clone();
        locus_text_listDaoConfig.initIdentityScope(type);

        locus_image_listDaoConfig = daoConfigMap.get(Locus_image_listDao.class).clone();
        locus_image_listDaoConfig.initIdentityScope(type);

        locus_sound_listDaoConfig = daoConfigMap.get(Locus_sound_listDao.class).clone();
        locus_sound_listDaoConfig.initIdentityScope(type);

        locus_number_listDaoConfig = daoConfigMap.get(Locus_number_listDao.class).clone();
        locus_number_listDaoConfig.initIdentityScope(type);

        disciplineDaoConfig = daoConfigMap.get(DisciplineDao.class).clone();
        disciplineDaoConfig.initIdentityScope(type);

        discipline_text_listDaoConfig = daoConfigMap.get(Discipline_text_listDao.class).clone();
        discipline_text_listDaoConfig.initIdentityScope(type);

        discipline_image_listDaoConfig = daoConfigMap.get(Discipline_image_listDao.class).clone();
        discipline_image_listDaoConfig.initIdentityScope(type);

        discipline_sound_listDaoConfig = daoConfigMap.get(Discipline_sound_listDao.class).clone();
        discipline_sound_listDaoConfig.initIdentityScope(type);

        discipline_number_listDaoConfig = daoConfigMap.get(Discipline_number_listDao.class).clone();
        discipline_number_listDaoConfig.initIdentityScope(type);

        runDaoConfig = daoConfigMap.get(RunDao.class).clone();
        runDaoConfig.initIdentityScope(type);

        run_discipline_item_listDaoConfig = daoConfigMap.get(Run_discipline_item_listDao.class).clone();
        run_discipline_item_listDaoConfig.initIdentityScope(type);

        dictionaryDaoConfig = daoConfigMap.get(DictionaryDao.class).clone();
        dictionaryDaoConfig.initIdentityScope(type);

        locusDao = new LocusDao(locusDaoConfig, this);
        locus_text_listDao = new Locus_text_listDao(locus_text_listDaoConfig, this);
        locus_image_listDao = new Locus_image_listDao(locus_image_listDaoConfig, this);
        locus_sound_listDao = new Locus_sound_listDao(locus_sound_listDaoConfig, this);
        locus_number_listDao = new Locus_number_listDao(locus_number_listDaoConfig, this);
        disciplineDao = new DisciplineDao(disciplineDaoConfig, this);
        discipline_text_listDao = new Discipline_text_listDao(discipline_text_listDaoConfig, this);
        discipline_image_listDao = new Discipline_image_listDao(discipline_image_listDaoConfig, this);
        discipline_sound_listDao = new Discipline_sound_listDao(discipline_sound_listDaoConfig, this);
        discipline_number_listDao = new Discipline_number_listDao(discipline_number_listDaoConfig, this);
        runDao = new RunDao(runDaoConfig, this);
        run_discipline_item_listDao = new Run_discipline_item_listDao(run_discipline_item_listDaoConfig, this);
        dictionaryDao = new DictionaryDao(dictionaryDaoConfig, this);

        registerDao(Locus.class, locusDao);
        registerDao(Locus_text_list.class, locus_text_listDao);
        registerDao(Locus_image_list.class, locus_image_listDao);
        registerDao(Locus_sound_list.class, locus_sound_listDao);
        registerDao(Locus_number_list.class, locus_number_listDao);
        registerDao(Discipline.class, disciplineDao);
        registerDao(Discipline_text_list.class, discipline_text_listDao);
        registerDao(Discipline_image_list.class, discipline_image_listDao);
        registerDao(Discipline_sound_list.class, discipline_sound_listDao);
        registerDao(Discipline_number_list.class, discipline_number_listDao);
        registerDao(Run.class, runDao);
        registerDao(Run_discipline_item_list.class, run_discipline_item_listDao);
        registerDao(Dictionary.class, dictionaryDao);
    }
    
    public void clear() {
        locusDaoConfig.getIdentityScope().clear();
        locus_text_listDaoConfig.getIdentityScope().clear();
        locus_image_listDaoConfig.getIdentityScope().clear();
        locus_sound_listDaoConfig.getIdentityScope().clear();
        locus_number_listDaoConfig.getIdentityScope().clear();
        disciplineDaoConfig.getIdentityScope().clear();
        discipline_text_listDaoConfig.getIdentityScope().clear();
        discipline_image_listDaoConfig.getIdentityScope().clear();
        discipline_sound_listDaoConfig.getIdentityScope().clear();
        discipline_number_listDaoConfig.getIdentityScope().clear();
        runDaoConfig.getIdentityScope().clear();
        run_discipline_item_listDaoConfig.getIdentityScope().clear();
        dictionaryDaoConfig.getIdentityScope().clear();
    }

    public LocusDao getLocusDao() {
        return locusDao;
    }

    public Locus_text_listDao getLocus_text_listDao() {
        return locus_text_listDao;
    }

    public Locus_image_listDao getLocus_image_listDao() {
        return locus_image_listDao;
    }

    public Locus_sound_listDao getLocus_sound_listDao() {
        return locus_sound_listDao;
    }

    public Locus_number_listDao getLocus_number_listDao() {
        return locus_number_listDao;
    }

    public DisciplineDao getDisciplineDao() {
        return disciplineDao;
    }

    public Discipline_text_listDao getDiscipline_text_listDao() {
        return discipline_text_listDao;
    }

    public Discipline_image_listDao getDiscipline_image_listDao() {
        return discipline_image_listDao;
    }

    public Discipline_sound_listDao getDiscipline_sound_listDao() {
        return discipline_sound_listDao;
    }

    public Discipline_number_listDao getDiscipline_number_listDao() {
        return discipline_number_listDao;
    }

    public RunDao getRunDao() {
        return runDao;
    }

    public Run_discipline_item_listDao getRun_discipline_item_listDao() {
        return run_discipline_item_listDao;
    }

    public DictionaryDao getDictionaryDao() {
        return dictionaryDao;
    }

}
