package com.kuviam.dopa.model;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "DICTIONARY".
 */
public class Dictionary {

    private Long id;
    /** Not-null value. */
    private String word;

    public Dictionary() {
    }

    public Dictionary(Long id) {
        this.id = id;
    }

    public Dictionary(Long id, String word) {
        this.id = id;
        this.word = word;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getWord() {
        return word;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setWord(String word) {
        this.word = word;
    }

}
