package com.kuviam.dopa.model;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "DISCIPLINE_TEXT_LIST".
 */
public class Discipline_text_list {

    private Long id;
    private long disciplineId;
    /** Not-null value. */
    private String item;

    public Discipline_text_list() {
    }

    public Discipline_text_list(Long id) {
        this.id = id;
    }

    public Discipline_text_list(Long id, long disciplineId, String item) {
        this.id = id;
        this.disciplineId = disciplineId;
        this.item = item;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public long getDisciplineId() {
        return disciplineId;
    }

    public void setDisciplineId(long disciplineId) {
        this.disciplineId = disciplineId;
    }

    /** Not-null value. */
    public String getItem() {
        return item;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setItem(String item) {
        this.item = item;
    }

}
