package com.kuviam.dopa.model;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "RUN_DISCIPLINE_ITEM_LIST".
 */
public class Run_discipline_item_list {

    private Long id;
    private long discipline_item;
    private Integer recall_attempt;
    private Integer practice_attempt;
    private long runId;
    private Boolean Status;
    private Long practice_time;
    private Long recall_time;

    public Run_discipline_item_list() {
    }

    public Run_discipline_item_list(Long id) {
        this.id = id;
    }

    public Run_discipline_item_list(Long id, long discipline_item, Integer recall_attempt, Integer practice_attempt, long runId, Boolean Status, Long practice_time, Long recall_time) {
        this.id = id;
        this.discipline_item = discipline_item;
        this.recall_attempt = recall_attempt;
        this.practice_attempt = practice_attempt;
        this.runId = runId;
        this.Status = Status;
        this.practice_time = practice_time;
        this.recall_time = recall_time;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public long getDiscipline_item() {
        return discipline_item;
    }

    public void setDiscipline_item(long discipline_item) {
        this.discipline_item = discipline_item;
    }

    public Integer getRecall_attempt() {
        return recall_attempt;
    }

    public void setRecall_attempt(Integer recall_attempt) {
        this.recall_attempt = recall_attempt;
    }

    public Integer getPractice_attempt() {
        return practice_attempt;
    }

    public void setPractice_attempt(Integer practice_attempt) {
        this.practice_attempt = practice_attempt;
    }

    public long getRunId() {
        return runId;
    }

    public void setRunId(long runId) {
        this.runId = runId;
    }

    public Boolean getStatus() {
        return Status;
    }

    public void setStatus(Boolean Status) {
        this.Status = Status;
    }

    public Long getPractice_time() {
        return practice_time;
    }

    public void setPractice_time(Long practice_time) {
        this.practice_time = practice_time;
    }

    public Long getRecall_time() {
        return recall_time;
    }

    public void setRecall_time(Long recall_time) {
        this.recall_time = recall_time;
    }

}
